var fraga = [
    {fraga:"Vad står HTML för?",
    alt_A:"Hyper Text Markup Language ",
    alt_B:"Hyper Trade Marketing Line",
    alt_C:"Hotmail",
    alt_D:"High Total Metanephrine Level ",
     svar:"A" },
    
    {fraga:"Vad står css för?",
    alt_A:"Counter style sheets",
    alt_B:"Cascading Sheet Style",
    alt_C:"Cascading Style Sheets",
    alt_D:"Cascading style set",
     svar:"C" },
  
    {fraga:"Vad gör taggen <br> ?",
    alt_A:"Den bryter inte raden så att texten du skriver efter kommer på nästa rad",
    alt_B:"Den bryter raden så att texten du skriver efter kommer på nästa rad. ",
    alt_C:"Den gör så att de blir stor bokstäver i raden.",
    alt_D:"Den stänger ner ditt program.",
     svar:"A" },
    
    {fraga:"Vad är det första man skriver i ett HTML dokument?",
    alt_A:"<head>",
    alt_B:"!START",
    alt_C:"!DOCTYPE",
    alt_D:"<html>",
     svar:"C" },
   
    {fraga:"Hur stänger man taggen <p> ?",
    alt_A:"Man skriver <stop>",
    alt_B:"Man skriver <br>",
    alt_C:"Man skriver </p>",
    alt_D:"Man trycker på Escape knappen",
     svar:"C" },
     
    {fraga:"Vad är felet i denna kod? <img src=pic_trulli.jpg alt=Italian Trulli>",
    alt_A:"Det saknas citationstecken",
    alt_B:"Det fel tagg som används",
    alt_C:"Trulli är inte ett fint hus. ",
    alt_D:"alt= måste vara samma som bildens src=",
     svar:"A" },
    
    {fraga:"Med hjälp av vilken tagg kommenterar du i html?",
    alt_A:"<  >",
    alt_B:"<!-- -->",
    alt_C:"<//  >",
    alt_D:"/* */",
     svar:"B" },
           
    {fraga:"Med hjälp av vilken tagg kommenterar du i CSS?",
    alt_A:"<  >",
    alt_B:"<!-- -->",
    alt_C:"<//  >",
    alt_D:"/* */",
     svar:"D" },   
    
    {fraga:" Hur ändrar man färg på taggen “h1” i css till färgen blå? - h1 {color: “blue”}",
    alt_A:"<h1=blue>",
    alt_B:"h1 is blue",
    alt_C:" h1 <color: blue>",
    alt_D:"h1 {color: blue}",
     svar:"D" },
            
    {fraga:"Hur ändrar man bakgrundsfärg till blå i html?",
    alt_A:"style=background-color:blue;",
    alt_B:"style=background-color=blue;",
    alt_C:"background-color:blue",
    alt_D:"Background-color=blue",
     svar:"A" },
            
    {fraga:"Hur kan man använda Å i html? å = &aring;",
    alt_A:"{a#’}",
    alt_B:"&aring;",
    alt_C:"<a+’>",
    alt_D:"a+ring",
     svar:"B" },
            
    {fraga:"Vad menas med webbdesign?",
    alt_A:"Att i ett program rita upp ett spindelnät",
    alt_B:"Att designa hur din webbläsare ska se ut, tex Google Chrome eller Mozilla Firefox",
    alt_C:"Att ge utseende och funktioner till en hemsida.",
    alt_D:"Att skapa ett program",
     svar:"C" },
            
    {fraga:"Finns det en skillnad mellan frontend och backend. Sant eller falskt?",
    alt_A:"Sant",
    alt_B:"Falskt",
    alt_C:"Kanske",
    alt_D:"Vet inte",
     svar:"A" },
            
    {fraga:"Med hjälp av vilken tagg gör man största möjliga rubrik?",
    alt_A:"<h1000>",
    alt_B:"<h100>",
    alt_C:"<h10>",
    alt_D:"<h1>",
     svar:"D" },
            
    {fraga:"Vad används taggen <ul> till? ",
    alt_A:"Att göra en ordnad lista.",
    alt_B:"Taggen finns inte.",
    alt_C:" Att göra en icke ordnad lista.",
    alt_D:"Att skapa en text med linje under (underline)",
     svar:"C" },
            
    {fraga:"Vad används taggen <ol> till?",
    alt_A:"Att skapa en text med linje över(overline)",
    alt_B:"Att göra en ordnad lista. ",
    alt_C:"Att göra en organiserad lista.",
    alt_D:"Att göra en icke ordnad lista.",
     svar:"B" },
            
    {fraga:" Vad är den korrekta taggen för att göra en checkbox? (kryssa-i-låda)",
    alt_A:"<checkbox>",
    alt_B:"<checkbox=true>",
    alt_C:"<input ''type=checkbox''>",
    alt_D:"<add checkbox>",
     svar:"C" },
    
     {fraga:"I vilken sektion skriver du in metadata?",
      alt_A:"I sektion <meta>",
      alt_B:"I sektion <head>",
      alt_C:"I sektion <body>",
      alt_D:"I sektion <info>",
      svar:"B"},
    
      {fraga:"Vad gör taggen <b>",
      alt_A:"Den gör en ny rad",
      alt_B:"Den skriver i fetstil",
      alt_C:"Den gör en rubrik",
      alt_D:"Taggen finns inte",
      svar:"B"},
         
      {fraga:"Vad gör taggen <i>?",
      alt_A:"Den ger kort info om koden",
      alt_B:"Den skriver i kursiv stil",
      alt_C:"Den gör en underrubrik",
      alt_D:"Taggen finns inte",
      svar:"B"},
        
      {fraga:"Vilken tagg används för att informera användare som inte har javascript aktiverat?",
      alt_A:"<noscript></noscript>",
      alt_B:"<nojava></nojava>",
      alt_C:"<javanf></javanf>",
      alt_D:"<javascript></javascript>",
      svar:"A"},
          
      {fraga:"Finns taggen <h6>?",
      alt_A:"Sant",
      alt_B:"Falskt",
      alt_C:"Kanske",
      alt_D:"Vet inte",
      svar:"A"},
          
      {fraga:"I vilken sektion ska man länka in css?",
      alt_A:"I <head>",
      alt_B:"I <body>",
      alt_C:"I <meta>",
      alt_D:"I <p>",
      svar:"A"},
          
      {fraga:"Vilken av dessa css syntax är korrekt för att göra så att alla <p> taggar blir i fetstil?",
      alt_A:"<p> {text-size:bold;}",
      alt_B:"<p style=''font-size:bold;''>",
      alt_C:"<p> {font-weight:bold;}",
      alt_D:"<p style=''text-size:bold;''>",
      svar:"C"},
          
      {fraga:"Hur lägger du till bakgrundsfärg för alla <h1> element?",
      alt_A:"h1 <background-color:#FFFFFF;>",
      alt_B:"<h1> {background-color:#FFFFFF;}",
      alt_C:"h1 {background-color:#FFFFFF;}",
      alt_D:"h1={background-color:#FFFFFF;}",
      svar:"C"},
          
      {fraga:"Hur gör du en lista som listar sina saker med rutor",
      alt_A:"list-style-type:cube;",
      alt_B:"list-style-type: square;",
      alt_C:"list-type: cube;",
      alt_D:"list-type: four;",
      svar:"B"},
      
       {fraga:"Hur väljer du ut ett element med id: demo?",
      alt_A:"id ''demo''",
      alt_B:"<demo>",
      alt_C:"#demo",
      alt_D:"!demo",
      svar:"C"},
       
       {fraga:"Vem/vilka skapade HTML?",
      alt_A:"Nicholas Drain",
      alt_B:"Tim Berners-Lee",
      alt_C:"Harry Tale och Martin Lee",
      alt_D:"Jeff Ahl",
      svar:"B"}, 
    
       {fraga:"Vilken tagg används för att definera viktig text?",
      alt_A:"<imp>",
      alt_B:"<define>",
      alt_C:"<it>",
      alt_D:"<strong>",
      svar:"D"},
     
       {fraga:"Vilken tagg används för att definera betonad text?",
      alt_A:"<em>",
      alt_B:"<et>",
      alt_C:"<defemp>",
      alt_D:"<det>",
      svar:"A"},
     
       {fraga:"Vilken kod är korrekt för att skapa en hyperlänk till google?",
      alt_A:"<a href=''http://www.google.com''>Google</a>",
      alt_B:"<href a=''http://www.google.com''>Google</a>",
      alt_C:"<a href=''http://www.google.com''</a>",
      alt_D:"<a href=''''>Google</a>",
      svar:"A"},
     
       {fraga:"Vilken symbol används för att indikera en sluttagg?",
      alt_A:";",
      alt_B:"/",
      alt_C:"#",
      alt_D:"&",
      svar:"B"},
     
       {fraga:"Vilken kod är korrekt för att göra en checkbox?",
      alt_A:"<input type=checkbox>",
      alt_B:"<input object=''checkbox''>",
      alt_C:"<input type=''checkbox''>",
      alt_D:"<input type ''checkbox''>",
      svar:"C"},
     
       {fraga:"Vilken kod är korrekt för att lägga in en bild?",
      alt_A:"<img src=''image.image'' ctrl=''MyImage">'',
      alt_B:"<img src=''image.gif'' ctrl=''MyImage">'',
      alt_C:"<img src=''image.image'' alt=''MyImage">'',
      alt_D:"<img src=''image.gif'' alt=''MyImage">'',
      svar:"D"},
     
       {fraga:"Vad gör taggen <title> ?",
      alt_A:"Det ger ett namn på själva webbläsarens flik.",
      alt_B:"Den gör en rubrik som blir lite större",
      alt_C:"Den gör stora bokstäver",
      alt_D:"Taggen finns inte",
      svar:"A"},
     
       {fraga:"Vilket HTML element definerar en titel för ett document?",
      alt_A:"<title>",
      alt_B:"<titel>",
      alt_C:"[title]",
      alt_D:"<insert title>",
      svar:"A"},
     
       {fraga:"Vilken doctype är korrekt för HTML5?",
      alt_A:"<!DOCTYPE html>",
      alt_B:"<!doctype html>",
      alt_C:"<insert html>",
      alt_D:"<!DOCTYPE>",
      svar:"A"},
     
       {fraga:"Vad gör taggen “<u>”?",
      alt_A:"Det är en understruken linje med text.",
      alt_B:"Det är den minsta sortens text.",
      alt_C:"Det är en underbar text,",
      alt_D:"Det är en understruken linje under text.",
      svar:"A"},
     
       {fraga:"Which input type defines a slider control?",
      alt_A:"Length ",
      alt_B:"Range",
      alt_C:"Slider",
      alt_D:"Strong",
      svar:"B"},
    
      {fraga:"Vilket HTML element definerar navigationslänkar?",
      alt_A:"<navigate>",
      alt_B:"<nav>",
      alt_C:"<navigation>",
      alt_D:"<nav.link>",
      svar:"B"},
    
      {fraga:"Vad gör taggen <pt>?",
      alt_A:"Den gör ett nytt stycke",
      alt_B:"Den gör en randomizer",
      alt_C:"Den gör text som endast visas under vissa tider ",
      alt_D:"Taggen finns inte",
      svar:"D"},
    

    
    
    ]